### ISSUE TITLE
Ikonka \ Knopka kopijuvannja perekladenogo tekstu.

### ISSUE THREAD

**Issue by Iipal** [jkramr/latynka-web#4]
Ja vykorystovuju cej servis dlja perevirky napysannja svojih nevelyčkyh tekstiv tomu knopka bystrogo kopijuvannja usjogo tekstu bula b duže dorečnoju.

Djakuju, Vy kruti!

**Comment by jkramr** [comment]
Djakuju za slušnu propozyciju! Sprobuju najblyžčym časom dodaty.

**Comment by jkramr** [comment]
dodano
